name: kwallet
description: Your friendly e-wallet

publish_to: 'none' 

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  lint: 1.7.2

flutter:

  uses-material-design: true
