name: kwallet
description: Your friendly e-wallet

publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.4.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_test:
    sdk: flutter
  json_serializable: ^6.1.4
  lint: 1.7.2

flutter:
  uses-material-design: true
